[project]
name = "cloudedx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.52.1",
]
