"""flatten listing contract

Revision ID: bf68daafc680
Revises: 116e4d8751a0
Create Date: 2026-08-14 09:15:23.590648+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'bf68daafc680'
down_revision: str | None = '116e4d8751a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_price_history_item_id'), table_name='item_price_history')
    op.drop_index(op.f('ix_item_price_history_recorded_at'), table_name='item_price_history')
    op.drop_table('item_price_history')
    op.add_column('items', sa.Column('category', sa.String(length=20), server_default='bag', nullable=False))
    op.drop_index(op.f('ix_items_model'), table_name='items')
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.drop_column('items', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('model', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.create_index(op.f('ix_items_model'), 'items', ['model'], unique=False)
    op.drop_column('items', 'category')
    op.create_table('item_price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_value', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_price_history_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_price_history'))
    )
    op.create_index(op.f('ix_item_price_history_recorded_at'), 'item_price_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_item_price_history_item_id'), 'item_price_history', ['item_id'], unique=False)
    # ### end Alembic commands ###
