"""add title cleaning columns

Revision ID: 9526e14250c0
Revises: 5f9d35bf779b
Create Date: 2026-08-12 19:53:01.664741+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9526e14250c0'
down_revision: str | None = '5f9d35bf779b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_brand', sa.String(length=20), nullable=True))
    op.add_column('items', sa.Column('clean_title', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('model', sa.String(length=40), nullable=True))
    op.add_column('items', sa.Column('is_usable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('items', sa.Column('reject_reason', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_items_is_usable'), 'items', ['is_usable'], unique=False)
    op.create_index(op.f('ix_items_model'), 'items', ['model'], unique=False)
    op.create_index(op.f('ix_items_search_brand'), 'items', ['search_brand'], unique=False)
    # ### end Alembic commands ###

    # 자동 생성분에 더한 데이터 보정.
    #
    # 이미 수집된 매물을 재정제한다. 안 하면 기존 데이터가 정제 전 상태로 남아
    # 브랜드가 틀린 채로 조회되고, 향수·쇼핑백이 계속 목록에 뜬다.
    #
    # 파이썬 함수를 SQL로 옮길 수 없으므로 여기서 앱 코드를 불러 한 행씩 처리한다.
    # 599건 기준 수 초면 끝난다. 데이터가 수십만 건이 되면 별도 배치로 빼야 한다.
    from app.domain.cleaning import clean_title

    connection = op.get_bind()
    rows = connection.execute(
        sa.text("SELECT id, title, brand FROM items")
    ).fetchall()

    for row in rows:
        cleaned = clean_title(row.title, search_brand=row.brand)

        connection.execute(
            sa.text(
                """
                UPDATE items
                   SET brand = :brand,
                       search_brand = :search_brand,
                       clean_title = :clean_title,
                       model = :model,
                       is_usable = :is_usable,
                       reject_reason = :reject_reason
                 WHERE id = :id
                """
            ),
            {
                "id": row.id,
                "brand": cleaned.brand or row.brand,
                "search_brand": row.brand,
                "clean_title": cleaned.clean_title,
                "model": cleaned.model,
                "is_usable": cleaned.is_usable,
                "reject_reason": cleaned.reject_reason,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_search_brand'), table_name='items')
    op.drop_index(op.f('ix_items_model'), table_name='items')
    op.drop_index(op.f('ix_items_is_usable'), table_name='items')
    op.drop_column('items', 'reject_reason')
    op.drop_column('items', 'is_usable')
    op.drop_column('items', 'model')
    op.drop_column('items', 'clean_title')
    op.drop_column('items', 'search_brand')
    # ### end Alembic commands ###
