"""add crawl runs table

Revision ID: df768b842473
Revises: 862c742d32c6
Create Date: 2026-08-11 14:48:23.655968+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'df768b842473'
down_revision: str | None = '862c742d32c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs'))
    )
    op.create_index(op.f('ix_crawl_runs_started_at'), 'crawl_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_started_at'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
