"""add parse health to crawl runs

Revision ID: 116e4d8751a0
Revises: aecf469c9411
Create Date: 2026-08-13 03:18:45.535565+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '116e4d8751a0'
down_revision: str | None = 'aecf469c9411'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_runs', sa.Column('parse_health', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_runs', 'parse_health')
    # ### end Alembic commands ###
