"""add seller type

Revision ID: aecf469c9411
Revises: 76af61b4ab4b
Create Date: 2026-08-13 02:00:29.747617+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'aecf469c9411'
down_revision: str | None = '76af61b4ab4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('seller_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'seller_type')
    # ### end Alembic commands ###
