"""add item lifecycle columns

Revision ID: 5f9d35bf779b
Revises: df768b842473
Create Date: 2026-08-12 08:04:52.390184+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5f9d35bf779b'
down_revision: str | None = 'df768b842473'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('items', sa.Column('missing_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('items', sa.Column('unavailable_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('items', sa.Column('unavailable_reason', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    # ### end Alembic commands ###

    # 자동 생성분에 더한 데이터 보정.
    #
    # 이미 판매완료로 수집된 매물을 소급 처리한다. 안 하면 기존 판매완료 매물이
    # is_active=true 로 남아 목록에 계속 노출된다 — 이 마이그레이션을 넣는 이유
    # 자체가 그걸 막으려는 것이라 여기서 함께 정리해야 한다.
    #
    # unavailable_at 은 last_seen_at 으로 채운다. 실제로 언제 팔렸는지는 알 수 없지만
    # "마지막으로 확인했을 때 이미 판매완료였다"는 사실은 맞고, NULL 로 두는 것보다
    # 정확에 가깝다.
    op.execute(
        """
        UPDATE items
           SET is_active = false,
               unavailable_at = last_seen_at,
               unavailable_reason = 'sold'
         WHERE is_sold = true
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_column('items', 'unavailable_reason')
    op.drop_column('items', 'unavailable_at')
    op.drop_column('items', 'missing_count')
    op.drop_column('items', 'is_active')
    # ### end Alembic commands ###
