"""create items table

Revision ID: 862c742d32c6
Revises: 
Create Date: 2026-08-11 07:13:02.835258+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '862c742d32c6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('price_value', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('time_text', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('url', name=op.f('uq_items_url'))
    )
    op.create_index(op.f('ix_items_brand'), 'items', ['brand'], unique=False)
    op.create_index(op.f('ix_items_posted_at'), 'items', ['posted_at'], unique=False)
    op.create_index(op.f('ix_items_price_value'), 'items', ['price_value'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_price_value'), table_name='items')
    op.drop_index(op.f('ix_items_posted_at'), table_name='items')
    op.drop_index(op.f('ix_items_brand'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
