"""add item price history

Revision ID: 76af61b4ab4b
Revises: 9526e14250c0
Create Date: 2026-08-13 00:49:40.491878+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '76af61b4ab4b'
down_revision: str | None = '9526e14250c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_value', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_price_history_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_price_history'))
    )
    op.create_index(op.f('ix_item_price_history_item_id'), 'item_price_history', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_price_history_recorded_at'), 'item_price_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###

    # 자동 생성분에 더한 데이터 보정.
    #
    # 이미 수집된 매물의 현재 가격을 기준선으로 넣는다. 안 하면 기존 매물은 다음에
    # 가격이 바뀔 때까지 이력이 비어 있고, "언제부터 이 가격이었나"에 답할 수 없다.
    #
    # recorded_at은 first_seen_at으로 잡는다. 지금 시각으로 넣으면 "오늘 이 가격이
    # 됐다"는 잘못된 사실이 되고, 3개월 전부터 같은 가격이던 매물이 신규처럼 보인다.
    # 실제로 그때 이 가격이었는지는 알 수 없지만, 최초 관측 시점이 가장 가까운 근사다.
    op.execute(
        """
        INSERT INTO item_price_history (item_id, price_value, recorded_at)
        SELECT id, price_value, first_seen_at
          FROM items
         WHERE price_value IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_price_history_recorded_at'), table_name='item_price_history')
    op.drop_index(op.f('ix_item_price_history_item_id'), table_name='item_price_history')
    op.drop_table('item_price_history')
    # ### end Alembic commands ###
